// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {game} from '../models';

export function ChordCell(arg1:number,arg2:number,arg3:number):Promise<game.BoardState>;

export function FlagCell(arg1:number,arg2:number,arg3:number):Promise<game.BoardState>;

export function GetBestTimes():Promise<game.BestTimes>;

export function NewGame(arg1:string):Promise<game.BoardState>;

export function OpenCell(arg1:number,arg2:number,arg3:number):Promise<game.BoardState>;

export function SubmitTime(arg1:string,arg2:number):Promise<game.BestTimes>;
