// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChordCell(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChordCell'](arg1, arg2, arg3);
}

export function FlagCell(arg1, arg2, arg3) {
  return window['go']['main']['App']['FlagCell'](arg1, arg2, arg3);
}

export function GetBestTimes() {
  return window['go']['main']['App']['GetBestTimes']();
}

export function NewGame(arg1) {
  return window['go']['main']['App']['NewGame'](arg1);
}

export function OpenCell(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenCell'](arg1, arg2, arg3);
}
